/**
 * Public contact form: `/api/contact/*`
 *
 * The only unauthenticated write endpoint in the application that creates a row
 * a human then has to read. That makes it the spam target, so most of this file
 * is the anti-abuse layer rather than the feature, and each layer is commented
 * with what it is actually for.
 *
 * The layers, in the order they run:
 *
 *   1. the feature flag:        an operator can close the door outright
 *   2. the account requirement: or leave it open only to members
 *   3. the honeypot:            catches form-filling bots, silently
 *   4. the minimum fill time:   catches scripted POSTs
 *   5. the length caps:         bounds what one submission can cost
 *   6. the per-IP hourly cap:   bounds how many one sender can make
 *
 * Cheap checks come first so a flood is refused before it reaches the database.
 * `optionalAuth` already ran in `createApp`, so `req.auth` is populated here for
 * a signed-in sender without this router paying for a second user lookup.
 */
import { Router } from 'express';
import { contactLimiter } from '../../middleware/rate-limit.js';
import { validate } from '../../middleware/validate.js';
import { asyncHandler, clientIp, clientUserAgent } from '../../lib/http.js';
import { recordAudit } from '../../lib/audit.js';
import { AppError, badRequest, forbidden, unauthorized } from '../../lib/errors.js';
import { getSettings } from '../../lib/settings.js';
import { contactSubmissionSchema, type ContactSubmissionInput } from './support.schemas.js';
import * as service from './support.service.js';

const router: Router = Router();

/**
 * How far in the future a client's clock may be and still be believed. Browser
 * clocks drift, and `startedAt` is generated by one. A minute of slack is the
 * difference between tolerating a skewed clock and accepting a fabricated
 * timestamp designed to look like a long, careful fill.
 */
const CLOCK_SKEW_MS = 60_000;

/**
 * A form open longer than this is stale rather than thoughtful. The window is
 * generous because people genuinely do leave a tab open over lunch, but it is
 * bounded so a single harvested `startedAt` cannot be replayed indefinitely.
 */
const MAX_FORM_AGE_MS = 12 * 60 * 60 * 1000;

/* -------------------------------------------------------------------------- */
/* Configuration                                                              */
/* -------------------------------------------------------------------------- */

/**
 * Everything the form needs to render itself, for a visitor with no session.
 *
 * `contactMaxPerHour` is published because the form can honestly say "three
 * messages an hour"; what is never published is how much of that allowance the
 * caller has already used. That number is the useful one to a spammer (it turns
 * the cap into an oracle they can poll to time the next wave), and it is useless
 * to a person, who is sending one message.
 */
router.get(
  '/config',
  asyncHandler(async (_req, res) => {
    const [support, features] = await Promise.all([
      getSettings('support'),
      getSettings('features'),
    ]);

    // Public editorial copy, identical for every visitor, and requested on every
    // render of the contact page.
    res.setHeader('Cache-Control', 'public, max-age=60');
    res.status(200).json({
      config: {
        enabled: features.contactFormEnabled,
        categories: support.categories,
        heading: support.contactHeading,
        intro: support.contactIntro,
        responseTimeNote: support.responseTimeNote,
        acknowledgement: support.acknowledgement,
        requiresAccount: support.contactRequiresAccount,
        maxMessageLength: support.contactMaxMessageLength,
        minFillSeconds: support.contactMinFillSeconds,
      },
    });
  }),
);

/* -------------------------------------------------------------------------- */
/* Submission                                                                 */
/* -------------------------------------------------------------------------- */

/**
 * `contactLimiter` and the per-IP database count both meter the same thing on
 * purpose, and neither replaces the other.
 *
 * The limiter is per-process memory: it costs nothing, it refuses a flood before
 * a connection is taken from the pool, and it forgets everything when the
 * process restarts or a second instance starts serving. The database count is a
 * real query, but it is the durable one: it survives a restart, it is shared
 * across instances, and it is the number an operator can actually configure from
 * the control panel. Cheap-and-forgetful in front, durable-and-authoritative
 * behind.
 */
router.post(
  '/',
  contactLimiter,
  validate({ body: contactSubmissionSchema }),
  asyncHandler(async (req, res) => {
    const input = req.body as ContactSubmissionInput;
    const [support, features] = await Promise.all([
      getSettings('support'),
      getSettings('features'),
    ]);

    /* --- 1. The feature flag ------------------------------------------- */

    // Independent of `ticketsEnabled`, so guest submissions can be closed during
    // a spam wave while signed-in users keep their support channel.
    if (!features.contactFormEnabled) {
      throw forbidden('The contact form is closed at the moment');
    }

    /* --- 2. The account requirement ------------------------------------ */

    const auth = req.auth ?? null;
    if (support.contactRequiresAccount && !auth) {
      throw unauthorized('Sign in to send a message through this form');
    }

    /*
     * The acknowledgement is built before any of the abuse checks run, because
     * the honeypot below has to answer with exactly this object. Anything
     * assembled only on the success path would eventually diverge from it.
     */
    const acknowledge = (ticketNumber: number): void => {
      /*
       * The reference number and the operator's copy, and nothing else.
       *
       * Echoing the submitted subject or message back would turn this endpoint
       * into a reflector: an attacker posts a payload, gets it returned, and now
       * has a URL on this origin that serves content they chose. It also gives a
       * spammer free confirmation that their text survived every filter above.
       */
      res.status(201).json({
        ticketNumber,
        acknowledgement: support.acknowledgement,
      });
    };

    /* --- 3. The honeypot ------------------------------------------------ */

    if (input.website.trim() !== '') {
      /*
       * A field no person can see was filled in, so the sender is a script.
       *
       * The response is deliberately indistinguishable from a real success:
       * telling a bot it was detected is free tuning feedback, and the operator
       * running it will simply stop filling that field and come back. Nothing is
       * written, nothing is audited: the whole point is that this request cost
       * us one string comparison.
       *
       * The number is fabricated. A bot never quotes a reference back, and
       * deriving a real-looking one would mean a database round trip on traffic
       * we have already decided to discard.
       */
      acknowledge(1000 + Math.floor(Math.random() * 9000));
      return;
    }

    /* --- 4. The minimum fill time --------------------------------------- */

    const elapsedMs = Date.now() - input.startedAt;

    if (elapsedMs < -CLOCK_SKEW_MS || elapsedMs > MAX_FORM_AGE_MS) {
      /*
       * A timestamp from the future, or from far enough in the past that the
       * page cannot still be the one the visitor is looking at. Both mean the
       * value was made up rather than captured, which is what a script does when
       * it has learned that instant submissions are refused.
       */
      throw badRequest('This form has expired. Please reload the page and try again.');
    }

    if (elapsedMs < support.contactMinFillSeconds * 1000) {
      /*
       * Nobody reads a form, types a subject and writes a message in under a few
       * seconds. A script posts in milliseconds, which is the entire signal,
       * and unlike a CAPTCHA it costs a real visitor nothing and needs no
       * third-party script on a page that promises it runs none.
       */
      throw badRequest('That was sent a little too quickly. Please try again in a moment.');
    }

    /* --- 5. The length caps --------------------------------------------- */

    // The schema already applied the structural ceilings. This is the operator's
    // own limit on top, which can be tightened from the control panel without a
    // redeploy when someone starts pasting novels into the queue.
    if (input.message.length > support.contactMaxMessageLength) {
      throw badRequest(
        `Please keep your message under ${support.contactMaxMessageLength} characters.`,
      );
    }

    if (!support.categories.includes(input.category)) {
      throw badRequest('Choose one of the listed categories', { categories: support.categories });
    }

    const name = input.name?.trim() ?? '';
    const email = input.email?.trim() ?? '';

    if (!auth && (!name || !email)) {
      // A guest submission with no way to reply to it is not a message; it is
      // litter in the queue.
      throw badRequest('Tell us your name and an email address so we can reply');
    }

    /* --- 6. The per-IP hourly cap --------------------------------------- */

    const ipAddress = clientIp(req);
    const recent = await service.countRecentContactSubmissions(ipAddress);

    if (recent >= support.contactMaxPerHour) {
      // Deliberately the last check: it is the only one that touches the
      // database, so everything cheaper has already had its chance to refuse.
      throw new AppError(
        429,
        'RATE_LIMITED',
        'You have sent several messages recently. Please wait a little before sending another.',
        { details: { retryAfterSeconds: 3600 } },
      );
    }

    /* --- Write ----------------------------------------------------------- */

    const ticket = await service.createContactTicket({
      subject: input.subject,
      category: input.category,
      message: input.message,
      userId: auth?.userId ?? null,
      // Guest details are stored only when there is no account to identify the
      // sender by. A signed-in sender is already reachable through their profile.
      guestName: auth ? null : name,
      guestEmail: auth ? null : email,
      authorName: auth?.username ?? name,
      ipAddress,
      userAgent: clientUserAgent(req),
    });

    await recordAudit(req, {
      action: 'contact.submit',
      targetType: 'ticket',
      targetId: ticket.id,
      // No name, address, subject or body. The audit trail records that a
      // submission happened and where from; the ticket itself is where the
      // content lives, and copying it here would duplicate personal data into a
      // table that is deliberately append-only and never purged.
      metadata: {
        number: ticket.number,
        category: input.category,
        authenticated: auth !== null,
        priorSubmissionsThisHour: recent,
      },
    });

    acknowledge(ticket.number);
  }),
);

export default router;
